### ISSUE TITLE
Output indents by 1 space after first line

### ISSUE THREAD

**Issue by rk** [MarkBennett/css-smasher#3]
I've concatenated multiple css files together through css-smash and I noticed that each line after line 1 starts with 1 space.

Example:

``` css
html, body {
 font-size:100%;
 }
 html, body, div, dl, dt, dd, ul, ol, li, h1, h2, h3, h4, h5, h6, p, a, abbr, acronym, address, cite, img, small, big, s, strike, sub, sup, pre, form, legend, fieldset, label, input, textarea, select, blockquote, q, table, caption, tbody, tfoot, thead, tr, th, td applet, object, iframe {
 margin:0;
 padding:0;
 border:0;
 outline:0;
 background:transparent;
 text-decoration:none;
 font-variant:normal;
 font-weight:normal;
 font-style:normal
 }
 /* ... */
body {
 background: #242424;
 font-family: Arial, Helvetica, sans-serif;
 }
```
